-- Delivery Report tables migrated into the main WMS Supabase project.
-- Transactional tables are structure-only at this stage.
-- Static/master tables below are seeded from the legacy Delivery Report project.

create table if not exists public.delivery_courier (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  is_active boolean default true
);

create table if not exists public.delivery_channel (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  is_active boolean default true
);

create table if not exists public.delivery_category (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  is_active boolean default true
);

create table if not exists public.delivery_courier_subclass (
  id bigint generated by default as identity primary key,
  courier_name text not null references public.delivery_courier(nama) on update cascade on delete restrict,
  courier_service text,
  is_active boolean default true
);

create table if not exists public.delivery_barcode_rules (
  id bigint generated by default as identity primary key,
  is_active boolean not null default true,
  rule_type text not null,
  pattern text,
  match_type text,
  result_value text references public.delivery_courier(nama) on update cascade on delete set null,
  priority smallint
);

create table if not exists public.delivery_order (
  id bigint generated by default as identity primary key,
  delivery_date date not null,
  delivery_category text,
  group_order text,
  channel text,
  part_no smallint,
  courier text,
  quantity integer,
  keterangan text,
  updated_time timestamp with time zone default now(),
  created_by text,
  updated_by text
);

create table if not exists public.delivery_barcode (
  barcode text primary key,
  timestamp_delivery timestamp with time zone,
  group_order text,
  courier text,
  is_defined boolean,
  timestamp_packing timestamp with time zone,
  packing_team text,
  is_packed boolean,
  is_delivered boolean,
  delivery_scanned_by text,
  packing_scanned_by text
);

create table if not exists public.delivery_retur_reason (
  id bigint generated by default as identity primary key,
  name text not null,
  reasoning_type text not null,
  is_active boolean default true
);

create table if not exists public.delivery_retur_action (
  id bigint generated by default as identity primary key,
  name text not null,
  requires_return boolean,
  requires_refund_value boolean,
  replacement_required boolean,
  is_active boolean default true
);

create table if not exists public.delivery_error_retur_cases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone default now(),
  tanggal_pengajuan timestamp with time zone,
  batas_tanggal_retur timestamp with time zone,
  group_order text,
  internal_external text,
  kode_kejadian text not null unique,
  order_id text,
  nama_customer text,
  no_handphone text,
  no_resi_pengiriman text references public.delivery_barcode(barcode) on update cascade on delete restrict,
  nomor_tim text,
  courier_name text references public.delivery_courier(nama) on update cascade on delete restrict,
  courier_service text,
  retur_reason text,
  retur_action text,
  produk_diretur text,
  produk_pengganti text,
  ongkir_masuk numeric,
  ongkir_keluar numeric,
  nilai_refund_kompensasi numeric,
  keterangan_tambahan text,
  status_barang text default 'Pending',
  total_retur numeric,
  alamat text,
  note_konsumen text,
  need_prioritized boolean default false,
  created_by text,
  updated_by text
);

create table if not exists public.delivery_order_issue (
  id bigint generated by default as identity primary key,
  name text,
  is_active boolean default true
);

create table if not exists public.delivery_order_handling (
  id bigint generated by default as identity primary key,
  name text,
  is_active boolean default true,
  is_pending boolean,
  add_cost boolean
);

create table if not exists public.delivery_order_issue_cases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone default now(),
  created_by text,
  updated_by text,
  group_order text,
  order_id text,
  nama text,
  no_hp numeric,
  produk_bermasalah text,
  alasan_bermasalah text,
  tindak_lanjut text,
  produk_pengganti text,
  tim text,
  biaya_timbul numeric,
  keterangan text
);

create table if not exists public.delivery_resi_manual (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  resi_manual text not null,
  nama text,
  no_hp text,
  alamat text,
  barang text,
  harga_paket text,
  nama_courier text references public.delivery_courier(nama) on update cascade on delete restrict,
  layanan_courier text,
  keterangan text,
  primary key (id, resi_manual)
);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'dir_user_profiles'
      and constraint_name = 'dir_user_profiles_display_name_key'
  ) then
    alter table public.dir_user_profiles
      add constraint dir_user_profiles_display_name_key unique (display_name);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'delivery_error_retur_cases_created_by_fkey'
  ) then
    alter table public.delivery_error_retur_cases
      add constraint delivery_error_retur_cases_created_by_fkey
      foreign key (created_by)
      references public.dir_user_profiles(display_name)
      on update cascade
      on delete restrict;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'delivery_order_issue_cases_created_by_fkey'
  ) then
    alter table public.delivery_order_issue_cases
      add constraint delivery_order_issue_cases_created_by_fkey
      foreign key (created_by)
      references public.dir_user_profiles(display_name)
      on update cascade
      on delete restrict;
  end if;
end $$;

create index if not exists delivery_order_date_idx on public.delivery_order (delivery_date);
create index if not exists delivery_order_group_idx on public.delivery_order (group_order);
create index if not exists delivery_order_category_idx on public.delivery_order (delivery_category);
create index if not exists delivery_order_courier_idx on public.delivery_order (courier);
create index if not exists delivery_barcode_delivery_ts_idx on public.delivery_barcode (timestamp_delivery);
create index if not exists delivery_barcode_packing_ts_idx on public.delivery_barcode (timestamp_packing);
create index if not exists delivery_barcode_group_idx on public.delivery_barcode (group_order);
create index if not exists delivery_barcode_courier_idx on public.delivery_barcode (courier);
create index if not exists delivery_error_retur_cases_submission_idx on public.delivery_error_retur_cases (tanggal_pengajuan);
create index if not exists delivery_error_retur_cases_deadline_idx on public.delivery_error_retur_cases (batas_tanggal_retur);
create index if not exists delivery_error_retur_cases_status_idx on public.delivery_error_retur_cases (status_barang);
create index if not exists delivery_error_retur_cases_created_by_idx on public.delivery_error_retur_cases (created_by);
create index if not exists delivery_error_retur_cases_group_idx on public.delivery_error_retur_cases (group_order);
create index if not exists delivery_order_issue_cases_created_idx on public.delivery_order_issue_cases (created_at);
create index if not exists delivery_order_issue_cases_created_by_idx on public.delivery_order_issue_cases (created_by);
create index if not exists delivery_order_issue_cases_group_idx on public.delivery_order_issue_cases (group_order);
create index if not exists delivery_resi_manual_created_idx on public.delivery_resi_manual (created_at);
create index if not exists delivery_resi_manual_courier_idx on public.delivery_resi_manual (nama_courier);

insert into public.delivery_courier (id, nama, is_active) values
  (1, 'J&T', true),
  (2, 'SICEPAT', true),
  (3, 'SPX', true),
  (4, 'JNE', true),
  (5, 'LION PARCEL', true),
  (6, 'POS INDONESIA', true),
  (7, 'SPX INSTANT/SAMEDAY', true),
  (8, 'GOJEK INSTANT/SAMEDAY', true),
  (9, 'GRAB INSTANT/SAMEDAY', true),
  (10, 'PAXEL', true),
  (11, 'LALAMOVE', true),
  (12, 'ID EXPRESS', true),
  (19, 'BLITZ-ID', true),
  (20, 'JNE CARGO', true),
  (21, 'J&T CARGO', true)
on conflict (id) do update set nama = excluded.nama, is_active = excluded.is_active;

insert into public.delivery_channel (id, nama, is_active) values
  (1, 'PLUGO', true),
  (2, 'TIKTOK', true),
  (3, 'SHOPEE', true),
  (4, 'TOKOPEDIA', true),
  (9, 'OTHER', true),
  (10, 'LIVE', true)
on conflict (id) do update set nama = excluded.nama, is_active = excluded.is_active;

insert into public.delivery_category (id, nama, is_active) values
  (1, 'REGULER', true),
  (2, 'RETURAN', true),
  (3, 'MANUAL', true),
  (4, 'GIVEAWAY', true),
  (5, 'ENDORSE', true),
  (9, 'PENDINGAN', true),
  (10, 'LIVE', true),
  (11, 'DROPSHIP', true)
on conflict (id) do update set nama = excluded.nama, is_active = excluded.is_active;

insert into public.delivery_courier_subclass (id, courier_name, courier_service, is_active) values
  (1, 'SICEPAT', 'REG', true),
  (2, 'SICEPAT', 'BEST', true),
  (3, 'J&T', 'EZVIP', true),
  (4, 'J&T', 'NEXT DAY', true),
  (5, 'JNE', 'REG', true),
  (6, 'JNE', 'YES', true)
on conflict (id) do update set courier_name = excluded.courier_name, courier_service = excluded.courier_service, is_active = excluded.is_active;

insert into public.delivery_barcode_rules (id, pattern, priority, is_active, rule_type, match_type, result_value) values
  (1, 'JX', 1, true, 'COURIER', 'PREFIX', 'J&T'),
  (7, 'JO', 1, true, 'COURIER', 'PREFIX', 'J&T'),
  (8, 'CM', 1, true, 'COURIER', 'PREFIX', 'JNE'),
  (10, 'CM', 1, true, 'COURIER', 'SUFFIX', 'JNE'),
  (11, 'SPX', 1, true, 'COURIER', 'PREFIX', 'SPX'),
  (12, 'SPX', 1, true, 'COURIER', 'SUFFIX', 'SPX'),
  (13, 'SIC', 1, true, 'COURIER', 'SUFFIX', 'SICEPAT'),
  (15, '0', 2, true, 'COURIER', 'PREFIX', 'SICEPAT'),
  (16, '3', 1, true, 'COURIER', 'PREFIX', 'SPX INSTANT/SAMEDAY'),
  (17, 'GK', 1, true, 'COURIER', 'PREFIX', 'GOJEK INSTANT/SAMEDAY'),
  (18, 'IN', 1, true, 'COURIER', 'PREFIX', 'GRAB INSTANT/SAMEDAY'),
  (19, 'BEM', 1, true, 'COURIER', 'PREFIX', 'BLITZ-ID'),
  (20, 'TG', 1, true, 'COURIER', 'PREFIX', 'JNE'),
  (21, '57', 1, true, 'COURIER', 'PREFIX', 'J&T CARGO'),
  (23, 'JX', 1, true, 'COURIER', 'SUFFIX', 'J&T'),
  (24, '9', 1, true, 'COURIER', 'PREFIX', 'SICEPAT'),
  (25, 'ID', 1, true, 'COURIER', 'PREFIX', 'SPX INSTANT/SAMEDAY'),
  (26, 'PAXEL', 1, true, 'COURIER', 'SUFFIX', 'PAXEL'),
  (27, 'JNE', 2, true, 'COURIER', 'SUFFIX', 'JNE'),
  (28, 'C1', 1, true, 'COURIER', 'PREFIX', 'LION PARCEL'),
  (29, 'SD', 1, true, 'COURIER', 'PREFIX', 'GRAB INSTANT/SAMEDAY'),
  (30, 'LALAMOVE', 1, true, 'COURIER', 'SUFFIX', 'LALAMOVE'),
  (31, 'GRAB INSTANT/SAMEDAY', 1, true, 'COURIER', 'SUFFIX', 'GRAB INSTANT/SAMEDAY'),
  (32, '58', 1, true, 'COURIER', 'PREFIX', 'GRAB INSTANT/SAMEDAY'),
  (33, 'JY', 1, true, 'COURIER', 'PREFIX', 'J&T')
on conflict (id) do update set pattern = excluded.pattern, priority = excluded.priority, is_active = excluded.is_active, rule_type = excluded.rule_type, match_type = excluded.match_type, result_value = excluded.result_value;

insert into public.delivery_order_handling (id, name, add_cost, is_active, is_pending) values
  (1, 'TETAP DIKIRIM TANPA KOMPENSASI', false, true, false),
  (2, 'TUKAR PRODUK/SIZE LAIN', false, true, false),
  (3, 'SUDAH DITEMUKAN', false, true, false),
  (4, 'REFUND', true, true, false),
  (5, 'PENDING', false, true, true),
  (6, 'PEMBERIAN VOUCHER/CASHBACK', true, true, false),
  (7, 'PENGIRIMAN PARTIAL', true, true, true),
  (8, 'MINTA STOCK MOB', false, true, false)
on conflict (id) do update set name = excluded.name, add_cost = excluded.add_cost, is_active = excluded.is_active, is_pending = excluded.is_pending;

insert into public.delivery_order_issue (id, name, is_active) values
  (1, 'REJECT', true),
  (2, 'BELUM/TIDAK DITEMUKAN', true),
  (3, 'BARANG BERADA DI BSD', true),
  (4, 'BEDA SIZING/INSEAM', true),
  (5, 'PLATFORM ERROR', true),
  (6, 'SALAH PACKING LIST', true),
  (7, 'MISS-STOCK', true),
  (8, 'SALAH INPUT STOCK', true),
  (9, 'TERKIRIM KE CUST LAIN', true),
  (10, 'KESALAHAN INFORMASI YANG DIBERIKAN KE CUSTOMER', true)
on conflict (id) do update set name = excluded.name, is_active = excluded.is_active;

insert into public.delivery_retur_action (id, name, is_active, requires_return, replacement_required, requires_refund_value) values
  (1, 'REFUND', true, true, false, true),
  (2, 'RETUR KE PRODUK/WARNA LAIN', true, true, true, null),
  (3, 'RETUR SESUAI PESANAN', true, true, true, false),
  (4, 'RETUR KE SIZE LAIN', true, true, true, false),
  (5, 'PEMBERIAN VOUCHER/CASHBACK', true, null, null, true),
  (6, 'MENGGANTI EKSPEDISI/PENGIRIMAN ULANG', true, false, false, false),
  (7, 'MENGIRIM PRODUK YANG KURANG', true, false, true, false)
on conflict (id) do update set name = excluded.name, is_active = excluded.is_active, requires_return = excluded.requires_return, replacement_required = excluded.replacement_required, requires_refund_value = excluded.requires_refund_value;

insert into public.delivery_retur_reason (id, name, is_active, reasoning_type) values
  (1, 'TUKAR SIZE (KEBESARAN)', true, 'EXTERNAL'),
  (2, 'TUKAR SIZE (KEKECILAN)', true, 'EXTERNAL'),
  (3, 'KURANG KIRIM', true, 'INTERNAL'),
  (4, 'LEBIH KIRIM', true, 'INTERNAL'),
  (5, 'KURANG COCOK', true, 'EXTERNAL'),
  (6, 'TIDAK DIKETAHUI', true, 'EXTERNAL'),
  (7, 'SALAH SIZE CHART', true, 'INTERNAL'),
  (8, 'TIDAK DAPAT MENERIMA TOLERANSI SIZE CHART', true, 'EXTERNAL'),
  (9, 'KENDALA EKSPEDISI', true, 'EXTERNAL'),
  (10, 'REJECT', true, 'INTERNAL'),
  (11, 'SALAH KIRIM', true, 'INTERNAL'),
  (12, 'KESALAHAN INFORMASI YANG DIBERIKAN KE CUSTOMER', true, 'INTERNAL')
on conflict (id) do update set name = excluded.name, is_active = excluded.is_active, reasoning_type = excluded.reasoning_type;

select setval(pg_get_serial_sequence('public.delivery_courier', 'id'), coalesce((select max(id) from public.delivery_courier), 1), true);
select setval(pg_get_serial_sequence('public.delivery_channel', 'id'), coalesce((select max(id) from public.delivery_channel), 1), true);
select setval(pg_get_serial_sequence('public.delivery_category', 'id'), coalesce((select max(id) from public.delivery_category), 1), true);
select setval(pg_get_serial_sequence('public.delivery_courier_subclass', 'id'), coalesce((select max(id) from public.delivery_courier_subclass), 1), true);
select setval(pg_get_serial_sequence('public.delivery_barcode_rules', 'id'), coalesce((select max(id) from public.delivery_barcode_rules), 1), true);
select setval(pg_get_serial_sequence('public.delivery_order_handling', 'id'), coalesce((select max(id) from public.delivery_order_handling), 1), true);
select setval(pg_get_serial_sequence('public.delivery_order_issue', 'id'), coalesce((select max(id) from public.delivery_order_issue), 1), true);
select setval(pg_get_serial_sequence('public.delivery_retur_action', 'id'), coalesce((select max(id) from public.delivery_retur_action), 1), true);
select setval(pg_get_serial_sequence('public.delivery_retur_reason', 'id'), coalesce((select max(id) from public.delivery_retur_reason), 1), true);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'delivery_courier',
    'delivery_channel',
    'delivery_category',
    'delivery_courier_subclass',
    'delivery_barcode_rules',
    'delivery_order',
    'delivery_barcode',
    'delivery_retur_reason',
    'delivery_retur_action',
    'delivery_error_retur_cases',
    'delivery_order_issue',
    'delivery_order_handling',
    'delivery_order_issue_cases',
    'delivery_resi_manual'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, public, authenticated, service_role', table_name);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);

    execute format('drop policy if exists %I on public.%I', 'delivery authenticated select', table_name);
    execute format('drop policy if exists %I on public.%I', 'delivery authenticated insert', table_name);
    execute format('drop policy if exists %I on public.%I', 'delivery authenticated update', table_name);
    execute format('drop policy if exists %I on public.%I', 'delivery authenticated delete', table_name);

    execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) is not null)', 'delivery authenticated select', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null)', 'delivery authenticated insert', table_name);
    execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null)', 'delivery authenticated update', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) is not null)', 'delivery authenticated delete', table_name);
  end loop;
end $$;

do $$
declare
  sequence_name text;
begin
  foreach sequence_name in array array[
    'delivery_courier_id_seq',
    'delivery_channel_id_seq',
    'delivery_category_id_seq',
    'delivery_courier_subclass_id_seq',
    'delivery_barcode_rules_id_seq',
    'delivery_order_id_seq',
    'delivery_retur_reason_id_seq',
    'delivery_retur_action_id_seq',
    'delivery_error_retur_cases_id_seq',
    'delivery_order_issue_id_seq',
    'delivery_order_handling_id_seq',
    'delivery_order_issue_cases_id_seq',
    'delivery_resi_manual_id_seq'
  ] loop
    execute format('revoke all on sequence public.%I from anon, public', sequence_name);
    execute format('grant usage, select on sequence public.%I to authenticated', sequence_name);
    execute format('grant usage, select on sequence public.%I to service_role', sequence_name);
  end loop;
end $$;
