begin;

create table if not exists public.hrd_leave_requests (
  id bigint generated by default as identity primary key,
  employee_authenticated_id uuid references auth.users(id) on delete set null,
  employee_name_snapshot text,
  employee_email_snapshot text not null,
  request_type text not null check (request_type in ('LEAVE', 'PERMIT')),
  start_date date not null,
  end_date date not null,
  reason text not null,
  status text not null default 'SUBMITTED' check (status in ('SUBMITTED', 'APPROVED', 'REJECTED')),
  submitted_at timestamptz not null default timezone('utc', now()),
  approved_at timestamptz,
  approved_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hrd_leave_requests_date_order_check check (end_date >= start_date)
);

create table if not exists public.hrd_birthday_gift_requests (
  id bigint generated by default as identity primary key,
  employee_authenticated_id uuid references auth.users(id) on delete set null,
  employee_name_snapshot text,
  employee_email_snapshot text not null,
  request_date date not null,
  notes text,
  status text not null default 'SUBMITTED' check (status in ('SUBMITTED', 'APPROVED', 'REJECTED')),
  submitted_at timestamptz not null default timezone('utc', now()),
  approved_at timestamptz,
  approved_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_hrd_leave_requests_employee
  on public.hrd_leave_requests (employee_authenticated_id, submitted_at desc);

create index if not exists idx_hrd_leave_requests_status
  on public.hrd_leave_requests (status, submitted_at desc);

create index if not exists idx_hrd_birthday_gift_requests_employee
  on public.hrd_birthday_gift_requests (employee_authenticated_id, submitted_at desc);

create index if not exists idx_hrd_birthday_gift_requests_status
  on public.hrd_birthday_gift_requests (status, submitted_at desc);

create or replace function public.hrga_actor_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''))
$$;

create or replace function public.hrga_is_admin()
returns boolean
language sql
stable
as $$
  select public.hrga_actor_email() = 'mr.peneliti@gmail.com'
$$;

create or replace function public.hrga_is_approver()
returns boolean
language sql
stable
as $$
  select
    public.hrga_is_admin()
    or exists (
      select 1
      from public.dir_user_profiles profile
      where profile.authenticated_id = auth.uid()
        and profile.role = 'hrga_approver'
    )
$$;

drop trigger if exists trg_hrd_leave_requests_updated_at on public.hrd_leave_requests;
create trigger trg_hrd_leave_requests_updated_at
before update on public.hrd_leave_requests
for each row execute function public.set_updated_at();

drop trigger if exists trg_hrd_birthday_gift_requests_updated_at on public.hrd_birthday_gift_requests;
create trigger trg_hrd_birthday_gift_requests_updated_at
before update on public.hrd_birthday_gift_requests
for each row execute function public.set_updated_at();

alter table public.hrd_leave_requests enable row level security;
alter table public.hrd_birthday_gift_requests enable row level security;

drop policy if exists "authenticated_select_hrd_leave_requests" on public.hrd_leave_requests;
drop policy if exists "authenticated_insert_hrd_leave_requests" on public.hrd_leave_requests;
drop policy if exists "authenticated_update_hrd_leave_requests" on public.hrd_leave_requests;
drop policy if exists "authenticated_delete_hrd_leave_requests" on public.hrd_leave_requests;

create policy "authenticated_select_hrd_leave_requests"
on public.hrd_leave_requests for select to authenticated
using (
  public.hrga_is_approver()
  or employee_authenticated_id = auth.uid()
);

create policy "authenticated_insert_hrd_leave_requests"
on public.hrd_leave_requests for insert to authenticated
with check (
  employee_authenticated_id = auth.uid()
  and status = 'SUBMITTED'
  and approved_at is null
  and approved_by is null
);

create policy "authenticated_update_hrd_leave_requests"
on public.hrd_leave_requests for update to authenticated
using (public.hrga_is_approver())
with check (public.hrga_is_approver());

create policy "authenticated_delete_hrd_leave_requests"
on public.hrd_leave_requests for delete to authenticated
using (
  public.hrga_is_approver()
  or (
    employee_authenticated_id = auth.uid()
    and status = 'SUBMITTED'
  )
);

drop policy if exists "authenticated_select_hrd_birthday_gift_requests" on public.hrd_birthday_gift_requests;
drop policy if exists "authenticated_insert_hrd_birthday_gift_requests" on public.hrd_birthday_gift_requests;
drop policy if exists "authenticated_update_hrd_birthday_gift_requests" on public.hrd_birthday_gift_requests;
drop policy if exists "authenticated_delete_hrd_birthday_gift_requests" on public.hrd_birthday_gift_requests;

create policy "authenticated_select_hrd_birthday_gift_requests"
on public.hrd_birthday_gift_requests for select to authenticated
using (
  public.hrga_is_approver()
  or employee_authenticated_id = auth.uid()
);

create policy "authenticated_insert_hrd_birthday_gift_requests"
on public.hrd_birthday_gift_requests for insert to authenticated
with check (
  employee_authenticated_id = auth.uid()
  and status = 'SUBMITTED'
  and approved_at is null
  and approved_by is null
);

create policy "authenticated_update_hrd_birthday_gift_requests"
on public.hrd_birthday_gift_requests for update to authenticated
using (public.hrga_is_approver())
with check (public.hrga_is_approver());

create policy "authenticated_delete_hrd_birthday_gift_requests"
on public.hrd_birthday_gift_requests for delete to authenticated
using (
  public.hrga_is_approver()
  or (
    employee_authenticated_id = auth.uid()
    and status = 'SUBMITTED'
  )
);

commit;
