-- Temporary sample breakdown workflow.
-- Samples remain as source rows in inbound_unload. Product details and QC
-- result splits are stored as child rows so QC task history stays intact.

begin;

alter table public.inbound_unload
  add column if not exists variant_name text,
  add column if not exists product_model_id bigint,
  add column if not exists product_model_variant_id bigint,
  add column if not exists is_product_temporary boolean not null default false,
  add column if not exists sample_resolved_at timestamp with time zone null,
  add column if not exists sample_resolved_by text null;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'inbound_unload'
      and constraint_name = 'inbound_unload_product_model_id_fkey'
  ) then
    alter table public.inbound_unload
      add constraint inbound_unload_product_model_id_fkey
      foreign key (product_model_id)
      references public.dir_product_models(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'inbound_unload'
      and constraint_name = 'inbound_unload_product_model_variant_id_fkey'
  ) then
    alter table public.inbound_unload
      add constraint inbound_unload_product_model_variant_id_fkey
      foreign key (product_model_variant_id)
      references public.dir_product_model_variants(id)
      on delete set null;
  end if;
end $$;

create index if not exists inbound_unload_product_model_id_idx
  on public.inbound_unload (product_model_id);

create index if not exists inbound_unload_product_model_variant_id_idx
  on public.inbound_unload (product_model_variant_id);

update public.inbound_unload
set
  is_product_temporary = true,
  model_name = coalesce(nullif(model_name, ''), 'TEMPORARY SAMPLE'),
  variant_name = coalesce(nullif(variant_name, ''), 'TEMPORARY'),
  updated_at = now()
where coalesce(is_sample, false) = true
  and (
    product_model_id is null
    or product_model_variant_id is null
    or upper(coalesce(model_name, '')) in ('', 'SAMPLE', 'TEMPORARY SAMPLE')
  );

create table if not exists public.inbound_sample_model_breakdowns (
  id bigint generated by default as identity primary key,
  inbound_unload_id bigint not null references public.inbound_unload(id) on update cascade on delete cascade,
  inbound_id bigint null references public.inbound(id) on update cascade on delete cascade,
  brand_id bigint null references public.dir_brands(id) on update cascade on delete set null,
  category_id bigint null references public.dir_categories(id) on update cascade on delete set null,
  product_model_id bigint null references public.dir_product_models(id) on update cascade on delete set null,
  product_model_variant_id bigint null references public.dir_product_model_variants(id) on update cascade on delete set null,
  model_name text not null,
  variant_name text null,
  photo_url text null,
  qty integer not null default 0 check (qty >= 0),
  created_by text null,
  updated_by text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists inbound_sample_model_breakdowns_unload_idx
  on public.inbound_sample_model_breakdowns (inbound_unload_id);

create index if not exists inbound_sample_model_breakdowns_inbound_idx
  on public.inbound_sample_model_breakdowns (inbound_id);

create index if not exists inbound_sample_model_breakdowns_product_model_idx
  on public.inbound_sample_model_breakdowns (product_model_id);

create index if not exists inbound_sample_model_breakdowns_variant_idx
  on public.inbound_sample_model_breakdowns (product_model_variant_id);

create or replace function public.set_inbound_sample_model_breakdown_defaults()
returns trigger
language plpgsql
as $$
declare
  source_row record;
  model_row record;
  variant_row record;
  next_breakdown_total integer;
begin
  select
    iu.id,
    iu.inbound_id,
    iu.brand_id,
    iu.category_id,
    iu.qty,
    iu.is_sample
  into source_row
  from public.inbound_unload iu
  where iu.id = new.inbound_unload_id;

  if not found then
    raise exception 'Inbound sample source % was not found.', new.inbound_unload_id;
  end if;

  if coalesce(source_row.is_sample, false) is not true then
    raise exception 'Inbound unload row % is not a sample row.', new.inbound_unload_id;
  end if;

  new.inbound_id := coalesce(new.inbound_id, source_row.inbound_id);
  new.brand_id := coalesce(new.brand_id, source_row.brand_id);
  new.category_id := coalesce(new.category_id, source_row.category_id);

  if new.product_model_variant_id is not null then
    select
      v.id,
      v.product_model_id,
      coalesce(nullif(v.selling_name, ''), nullif(v.variant_name, ''), nullif(v.variant_label, ''), nullif(v.variant_code, '')) as display_variant_name,
      v.variant_photo_url
    into variant_row
    from public.dir_product_model_variants v
    where v.id = new.product_model_variant_id;

    if not found then
      raise exception 'Product model variant % was not found.', new.product_model_variant_id;
    end if;

    new.product_model_id := coalesce(new.product_model_id, variant_row.product_model_id);
    new.variant_name := coalesce(nullif(new.variant_name, ''), variant_row.display_variant_name);
    new.photo_url := coalesce(nullif(new.photo_url, ''), variant_row.variant_photo_url);
  end if;

  if new.product_model_id is not null then
    select
      m.id,
      m.model_name,
      m.brand_id,
      m.category_id
    into model_row
    from public.dir_product_models m
    where m.id = new.product_model_id;

    if not found then
      raise exception 'Product model % was not found.', new.product_model_id;
    end if;

    if new.product_model_variant_id is not null and variant_row.product_model_id <> model_row.id then
      raise exception 'Variant % does not belong to model %.', new.product_model_variant_id, new.product_model_id;
    end if;

    new.model_name := coalesce(nullif(new.model_name, ''), model_row.model_name);
    new.brand_id := coalesce(new.brand_id, model_row.brand_id);
    new.category_id := coalesce(new.category_id, model_row.category_id);
  end if;

  if nullif(new.model_name, '') is null then
    raise exception 'Model name is required for sample model breakdown.';
  end if;

  select coalesce(sum(qty), 0)
  into next_breakdown_total
  from public.inbound_sample_model_breakdowns
  where inbound_unload_id = new.inbound_unload_id
    and id <> coalesce(new.id, 0);

  next_breakdown_total := next_breakdown_total + new.qty;

  if next_breakdown_total > coalesce(source_row.qty, 0) then
    raise exception 'Sample model breakdown total % cannot exceed sample qty % for inbound unload row %.', next_breakdown_total, source_row.qty, new.inbound_unload_id;
  end if;

  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_set_inbound_sample_model_breakdown_defaults
  on public.inbound_sample_model_breakdowns;

create trigger trg_set_inbound_sample_model_breakdown_defaults
before insert or update on public.inbound_sample_model_breakdowns
for each row
execute function public.set_inbound_sample_model_breakdown_defaults();

create table if not exists public.qc_sample_breakdowns (
  id bigint generated by default as identity primary key,
  qc_item_id bigint not null references public.qc_items(id) on update cascade on delete cascade,
  sample_breakdown_id bigint not null references public.inbound_sample_model_breakdowns(id) on update cascade on delete cascade,
  qty_a integer not null default 0 check (qty_a >= 0),
  qty_b integer not null default 0 check (qty_b >= 0),
  qty_c integer not null default 0 check (qty_c >= 0),
  created_by text null,
  updated_by text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint qc_sample_breakdowns_unique_split
    unique (qc_item_id, sample_breakdown_id)
);

create index if not exists qc_sample_breakdowns_qc_item_idx
  on public.qc_sample_breakdowns (qc_item_id);

create index if not exists qc_sample_breakdowns_sample_breakdown_idx
  on public.qc_sample_breakdowns (sample_breakdown_id);

create or replace function public.validate_qc_sample_breakdown()
returns trigger
language plpgsql
as $$
declare
  qc_row record;
  sample_row record;
  split_total integer;
  model_split_total integer;
  checked_total integer;
begin
  select
    qi.id,
    qi.inbound_unload_id,
    coalesce(qi.qty_a, 0) as qty_a,
    coalesce(qi.qty_b, 0) as qty_b,
    coalesce(qi.qty_c, 0) as qty_c
  into qc_row
  from public.qc_items qi
  where qi.id = new.qc_item_id;

  if not found then
    raise exception 'QC item % was not found.', new.qc_item_id;
  end if;

  select
    b.id,
    b.inbound_unload_id,
    b.qty
  into sample_row
  from public.inbound_sample_model_breakdowns b
  where b.id = new.sample_breakdown_id;

  if not found then
    raise exception 'Sample breakdown % was not found.', new.sample_breakdown_id;
  end if;

  if qc_row.inbound_unload_id <> sample_row.inbound_unload_id then
    raise exception 'QC item % and sample breakdown % do not belong to the same sample source.', new.qc_item_id, new.sample_breakdown_id;
  end if;

  checked_total := qc_row.qty_a + qc_row.qty_b + qc_row.qty_c;

  select coalesce(sum(qsb.qty_a + qsb.qty_b + qsb.qty_c), 0)
  into split_total
  from public.qc_sample_breakdowns qsb
  where qsb.qc_item_id = new.qc_item_id
    and qsb.id <> coalesce(new.id, 0);

  split_total := split_total + new.qty_a + new.qty_b + new.qty_c;

  if split_total > checked_total then
    raise exception 'QC sample split total % cannot exceed checked qty % for QC item %.', split_total, checked_total, new.qc_item_id;
  end if;

  select coalesce(sum(qsb.qty_a + qsb.qty_b + qsb.qty_c), 0)
  into model_split_total
  from public.qc_sample_breakdowns qsb
  where qsb.sample_breakdown_id = new.sample_breakdown_id
    and qsb.id <> coalesce(new.id, 0);

  model_split_total := model_split_total + new.qty_a + new.qty_b + new.qty_c;

  if model_split_total > coalesce(sample_row.qty, 0) then
    raise exception 'QC sample split total % cannot exceed model breakdown qty % for sample breakdown %.', model_split_total, sample_row.qty, new.sample_breakdown_id;
  end if;

  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_validate_qc_sample_breakdown
  on public.qc_sample_breakdowns;

create trigger trg_validate_qc_sample_breakdown
before insert or update on public.qc_sample_breakdowns
for each row
execute function public.validate_qc_sample_breakdown();

create or replace view public.inbound_sample_resolution_status as
with model_totals as (
  select
    inbound_unload_id,
    count(*) as model_row_count,
    coalesce(sum(qty), 0) as model_breakdown_qty
  from public.inbound_sample_model_breakdowns
  group by inbound_unload_id
),
qc_totals as (
  select
    inbound_unload_id,
    count(*) as qc_item_count,
    coalesce(sum(coalesce(qty_a, 0) + coalesce(qty_b, 0) + coalesce(qty_c, 0)), 0) as qc_checked_qty
  from public.qc_items
  group by inbound_unload_id
),
qc_split_totals as (
  select
    b.inbound_unload_id,
    count(*) as qc_split_row_count,
    coalesce(sum(coalesce(qsb.qty_a, 0) + coalesce(qsb.qty_b, 0) + coalesce(qsb.qty_c, 0)), 0) as qc_split_qty
  from public.qc_sample_breakdowns qsb
  join public.inbound_sample_model_breakdowns b
    on b.id = qsb.sample_breakdown_id
  group by b.inbound_unload_id
)
select
  iu.id as inbound_unload_id,
  iu.inbound_id,
  iu.koli_sequence,
  iu.qty as sample_qty,
  coalesce(iu.is_product_temporary, false) as is_product_temporary,
  coalesce(mt.model_row_count, 0) as model_row_count,
  coalesce(mt.model_breakdown_qty, 0) as model_breakdown_qty,
  coalesce(qt.qc_item_count, 0) as qc_item_count,
  coalesce(qt.qc_checked_qty, 0) as qc_checked_qty,
  coalesce(qst.qc_split_row_count, 0) as qc_split_row_count,
  coalesce(qst.qc_split_qty, 0) as qc_split_qty,
  coalesce(mt.model_breakdown_qty, 0) = coalesce(iu.qty, 0) as is_model_resolved,
  (
    coalesce(qt.qc_checked_qty, 0) = 0
    or coalesce(qst.qc_split_qty, 0) = coalesce(qt.qc_checked_qty, 0)
  ) as is_qc_split_resolved,
  (
    coalesce(mt.model_breakdown_qty, 0) = coalesce(iu.qty, 0)
    and (
      coalesce(qt.qc_checked_qty, 0) = 0
      or coalesce(qst.qc_split_qty, 0) = coalesce(qt.qc_checked_qty, 0)
    )
  ) as is_sample_resolved
from public.inbound_unload iu
left join model_totals mt
  on mt.inbound_unload_id = iu.id
left join qc_totals qt
  on qt.inbound_unload_id = iu.id
left join qc_split_totals qst
  on qst.inbound_unload_id = iu.id
where coalesce(iu.is_sample, false) = true;

alter table public.inbound_sample_model_breakdowns enable row level security;
alter table public.qc_sample_breakdowns enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.inbound_sample_model_breakdowns to authenticated;
grant select, insert, update, delete on public.qc_sample_breakdowns to authenticated;
grant select on public.inbound_sample_resolution_status to authenticated;

do $$
begin
  if to_regclass('public.inbound_sample_model_breakdowns_id_seq') is not null then
    grant usage, select on sequence public.inbound_sample_model_breakdowns_id_seq to authenticated;
  end if;

  if to_regclass('public.qc_sample_breakdowns_id_seq') is not null then
    grant usage, select on sequence public.qc_sample_breakdowns_id_seq to authenticated;
  end if;
end $$;

drop policy if exists inbound_sample_model_breakdowns_authenticated_select
  on public.inbound_sample_model_breakdowns;
drop policy if exists inbound_sample_model_breakdowns_authenticated_insert
  on public.inbound_sample_model_breakdowns;
drop policy if exists inbound_sample_model_breakdowns_authenticated_update
  on public.inbound_sample_model_breakdowns;
drop policy if exists inbound_sample_model_breakdowns_authenticated_delete
  on public.inbound_sample_model_breakdowns;

create policy inbound_sample_model_breakdowns_authenticated_select
on public.inbound_sample_model_breakdowns
for select
to authenticated
using (true);

create policy inbound_sample_model_breakdowns_authenticated_insert
on public.inbound_sample_model_breakdowns
for insert
to authenticated
with check (true);

create policy inbound_sample_model_breakdowns_authenticated_update
on public.inbound_sample_model_breakdowns
for update
to authenticated
using (true)
with check (true);

create policy inbound_sample_model_breakdowns_authenticated_delete
on public.inbound_sample_model_breakdowns
for delete
to authenticated
using (true);

drop policy if exists qc_sample_breakdowns_authenticated_select
  on public.qc_sample_breakdowns;
drop policy if exists qc_sample_breakdowns_authenticated_insert
  on public.qc_sample_breakdowns;
drop policy if exists qc_sample_breakdowns_authenticated_update
  on public.qc_sample_breakdowns;
drop policy if exists qc_sample_breakdowns_authenticated_delete
  on public.qc_sample_breakdowns;

create policy qc_sample_breakdowns_authenticated_select
on public.qc_sample_breakdowns
for select
to authenticated
using (true);

create policy qc_sample_breakdowns_authenticated_insert
on public.qc_sample_breakdowns
for insert
to authenticated
with check (true);

create policy qc_sample_breakdowns_authenticated_update
on public.qc_sample_breakdowns
for update
to authenticated
using (true)
with check (true);

create policy qc_sample_breakdowns_authenticated_delete
on public.qc_sample_breakdowns
for delete
to authenticated
using (true);

comment on column public.inbound_unload.is_product_temporary is
  'True when a sample is intentionally entered without final model or variant detail yet.';

comment on table public.inbound_sample_model_breakdowns is
  'Final model and variant breakdown for a temporary inbound sample row.';

comment on table public.qc_sample_breakdowns is
  'QC-owned split of temporary sample QC results into final sample model breakdown rows.';

commit;
