begin;

create table if not exists public.pl_general_photos (
  id bigint generated by default as identity primary key,
  inbound_id bigint not null references public.inbound(id) on delete cascade,
  page_group_key text not null,
  photo_url text not null,
  display_order integer not null default 1,
  source_product_model_id bigint null references public.dir_product_models(id) on delete set null,
  source_product_model_variant_id bigint null references public.dir_product_model_variants(id) on delete set null,
  uploaded_by text null,
  created_at timestamp with time zone not null default now(),
  constraint pl_general_photos_page_group_key_check check (btrim(page_group_key) <> ''),
  constraint pl_general_photos_photo_url_check check (btrim(photo_url) <> ''),
  constraint pl_general_photos_display_order_check check (display_order >= 1),
  constraint pl_general_photos_inbound_group_url_uidx unique (inbound_id, page_group_key, photo_url)
);

create index if not exists pl_general_photos_scope_idx
  on public.pl_general_photos (inbound_id, page_group_key, display_order, id);

alter table public.pl_general_photos enable row level security;

drop policy if exists "Allow all PL general photos select" on public.pl_general_photos;
drop policy if exists "Allow all PL general photos insert" on public.pl_general_photos;
drop policy if exists "Allow all PL general photos update" on public.pl_general_photos;
drop policy if exists "Allow all PL general photos delete" on public.pl_general_photos;

create policy "Allow all PL general photos select"
  on public.pl_general_photos for select
  using (true);

create policy "Allow all PL general photos insert"
  on public.pl_general_photos for insert
  with check (true);

create policy "Allow all PL general photos update"
  on public.pl_general_photos for update
  using (true)
  with check (true);

create policy "Allow all PL general photos delete"
  on public.pl_general_photos for delete
  using (true);

commit;
