drop table if exists public.pl_packing_items;

create table public.pl_packing_items (
  id bigint generated by default as identity primary key,
  inbound_id bigint not null references public.inbound(id) on delete cascade,
  pl_size_breakdown_id bigint not null references public.pl_size_breakdown(id) on delete restrict,
  packing_group_key text not null,
  storing_type text not null default 'MOB',
  package_type text not null default 'REGULAR',
  brand_code text null,
  product_model_id bigint null references public.dir_product_models(id) on delete set null,
  product_model_variant_id bigint null references public.dir_product_model_variants(id) on delete set null,
  source_variant_code text null,
  pl_detail_seq integer null,
  detail_order integer null,
  pl_name text null,
  model_name text null,
  variant_name text null,
  size_label text not null,
  koli_sequence integer null,
  qty integer not null default 0,
  packed_by text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pl_packing_items_qty_check check (qty >= 0),
  constraint pl_packing_items_koli_sequence_check check (koli_sequence is null or koli_sequence >= 1),
  constraint pl_packing_items_storing_type_check check (storing_type in ('MOB', 'OI')),
  constraint pl_packing_items_package_type_check check (package_type in ('REGULAR', 'PHOTO')),
  constraint pl_packing_items_photo_koli_check check (
    (package_type = 'PHOTO' and koli_sequence is null)
    or
    (package_type = 'REGULAR' and koli_sequence is not null)
  )
);

create index pl_packing_items_inbound_idx
  on public.pl_packing_items (inbound_id, storing_type, package_type, brand_code, koli_sequence);

create index pl_packing_items_group_idx
  on public.pl_packing_items (packing_group_key);

create index pl_packing_items_breakdown_idx
  on public.pl_packing_items (pl_size_breakdown_id);

create index pl_packing_items_model_idx
  on public.pl_packing_items (product_model_id, product_model_variant_id);

alter table public.pl_packing_items enable row level security;

drop policy if exists "Allow all pl packing items select" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items insert" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items update" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items delete" on public.pl_packing_items;

create policy "Allow all pl packing items select"
  on public.pl_packing_items for select
  using (true);

create policy "Allow all pl packing items insert"
  on public.pl_packing_items for insert
  with check (true);

create policy "Allow all pl packing items update"
  on public.pl_packing_items for update
  using (true)
  with check (true);

create policy "Allow all pl packing items delete"
  on public.pl_packing_items for delete
  using (true);
