create table if not exists public.pl_packing_items (
  id bigint generated by default as identity primary key,
  inbound_id bigint not null references public.inbound(id) on delete cascade,
  pl_size_breakdown_id bigint not null references public.pl_size_breakdown(id) on delete restrict,
  packing_group_key text null,
  storing_type text not null default 'MOB',
  package_type text not null default 'REGULAR',
  brand_id bigint null,
  product_model_id bigint null,
  product_model_variant_id bigint null,
  source_variant_code text null,
  pl_detail_seq integer null,
  detail_order integer null,
  pl_name text null,
  model_name text null,
  variant_name text null,
  size_label text not null,
  koli_sequence integer null,
  koli_label text not null default '-',
  qty integer not null default 0,
  packed_by text null,
  posted_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pl_packing_items_qty_check check (qty >= 0),
  constraint pl_packing_items_koli_sequence_check check (koli_sequence is null or koli_sequence >= 1),
  constraint pl_packing_items_storing_type_check check (storing_type in ('MOB', 'OI')),
  constraint pl_packing_items_package_type_check check (package_type in ('REGULAR', 'PHOTO'))
);

alter table public.pl_packing_items
  add column if not exists packing_group_key text,
  add column if not exists storing_type text not null default 'MOB',
  add column if not exists package_type text not null default 'REGULAR',
  add column if not exists brand_id bigint,
  add column if not exists koli_label text not null default '-',
  add column if not exists posted_at timestamp with time zone;

alter table public.pl_packing_items
  alter column koli_sequence drop not null;

alter table public.pl_packing_items
  drop constraint if exists pl_packing_items_qty_check,
  drop constraint if exists pl_packing_items_koli_sequence_check,
  drop constraint if exists pl_packing_items_storing_type_check,
  drop constraint if exists pl_packing_items_package_type_check;

alter table public.pl_packing_items
  add constraint pl_packing_items_qty_check check (qty >= 0),
  add constraint pl_packing_items_koli_sequence_check check (koli_sequence is null or koli_sequence >= 1),
  add constraint pl_packing_items_storing_type_check check (storing_type in ('MOB', 'OI')),
  add constraint pl_packing_items_package_type_check check (package_type in ('REGULAR', 'PHOTO'));

drop index if exists public.pl_packing_items_breakdown_koli_uidx;

create index if not exists pl_packing_items_inbound_idx
  on public.pl_packing_items (inbound_id, storing_type, package_type, brand_id, koli_sequence);

create index if not exists pl_packing_items_group_idx
  on public.pl_packing_items (packing_group_key);

create index if not exists pl_packing_items_breakdown_idx
  on public.pl_packing_items (pl_size_breakdown_id);

alter table public.pl_packing_items enable row level security;

drop policy if exists "Allow all pl packing items select" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items insert" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items update" on public.pl_packing_items;
drop policy if exists "Allow all pl packing items delete" on public.pl_packing_items;

create policy "Allow all pl packing items select"
  on public.pl_packing_items for select
  using (true);

create policy "Allow all pl packing items insert"
  on public.pl_packing_items for insert
  with check (true);

create policy "Allow all pl packing items update"
  on public.pl_packing_items for update
  using (true)
  with check (true);

create policy "Allow all pl packing items delete"
  on public.pl_packing_items for delete
  using (true);
