-- Shelving Queue for quantities picked above the original restock request.
-- The original restock_request.qty remains unchanged.

create table if not exists public.warehouse_shelving_queue (
  id bigint generated by default as identity primary key,
  restock_request_id uuid null references public.restock_request(id) on delete set null,
  source_storage_id bigint null,
  source_location_label text null,
  source_pl_packing_item_id bigint null,
  sku_id text null,
  source_variant_code text null,
  item_name text not null,
  size text null,
  group_code text not null default 'MOB',
  qty integer not null check (qty > 0),
  target_rack_location_id bigint null,
  status text not null default 'WAITING_SHELVING'
    check (status in ('WAITING_SHELVING', 'STORED', 'CANCELLED')),
  notes text null,
  created_at timestamptz not null default timezone('utc', now()),
  created_by text null,
  stored_at timestamptz null,
  stored_by text null
);

create index if not exists warehouse_shelving_queue_status_created_idx
  on public.warehouse_shelving_queue (status, created_at desc);

create index if not exists warehouse_shelving_queue_request_idx
  on public.warehouse_shelving_queue (restock_request_id);

create index if not exists warehouse_shelving_queue_group_idx
  on public.warehouse_shelving_queue (group_code, status);

alter table public.warehouse_shelving_queue enable row level security;

grant select, insert, update, delete on public.warehouse_shelving_queue to authenticated;
grant usage, select on sequence public.warehouse_shelving_queue_id_seq to authenticated;

drop policy if exists warehouse_shelving_queue_authenticated_select on public.warehouse_shelving_queue;
create policy warehouse_shelving_queue_authenticated_select
on public.warehouse_shelving_queue
for select to authenticated
using (true);

drop policy if exists warehouse_shelving_queue_authenticated_insert on public.warehouse_shelving_queue;
create policy warehouse_shelving_queue_authenticated_insert
on public.warehouse_shelving_queue
for insert to authenticated
with check (true);

drop policy if exists warehouse_shelving_queue_authenticated_update on public.warehouse_shelving_queue;
create policy warehouse_shelving_queue_authenticated_update
on public.warehouse_shelving_queue
for update to authenticated
using (true)
with check (true);

drop policy if exists warehouse_shelving_queue_authenticated_delete on public.warehouse_shelving_queue;
create policy warehouse_shelving_queue_authenticated_delete
on public.warehouse_shelving_queue
for delete to authenticated
using (true);

alter table public.warehouse_storage_movements
  drop constraint if exists warehouse_storage_movements_type_check;

alter table public.warehouse_storage_movements
  add constraint warehouse_storage_movements_type_check
  check (movement_type in ('STORE_QUEUE', 'MOVE', 'TAKE_OUT', 'TEMPORARY_IN', 'TEMPORARY_RETURN', 'PUTAWAY_IN'));

comment on table public.warehouse_shelving_queue is
  'Excess quantities picked above a restock request, awaiting shelving confirmation.';
