-- Temporary Sales Area discrepancy / physical count reconciliation.
-- Safe to run repeatedly. This script does not delete or overwrite existing data.

create table if not exists public.warehouse_temporary_sales_adjustments (
  id bigint generated by default as identity primary key,
  temporary_sales_item_id bigint not null
    references public.warehouse_temporary_sales_items(id) on delete cascade,
  system_qty numeric not null check (system_qty >= 0),
  actual_qty numeric not null check (actual_qty >= 0),
  variance_qty numeric not null,
  reason text,
  created_by text,
  created_at timestamptz not null default now(),
  constraint warehouse_temporary_sales_adjustments_variance_check
    check (variance_qty = actual_qty - system_qty)
);

create index if not exists warehouse_temporary_sales_adjustments_item_idx
  on public.warehouse_temporary_sales_adjustments (temporary_sales_item_id, created_at desc);

alter table public.warehouse_storage_movements
  drop constraint if exists warehouse_storage_movements_type_check;

alter table public.warehouse_storage_movements
  add constraint warehouse_storage_movements_type_check
  check (
    movement_type in (
      'STORE_QUEUE',
      'MOVE',
      'TAKE_OUT',
      'TEMPORARY_IN',
      'TEMPORARY_RETURN',
      'TEMPORARY_ADJUSTMENT_IN',
      'TEMPORARY_ADJUSTMENT_OUT'
    )
  );

alter table public.warehouse_temporary_sales_adjustments enable row level security;

grant select, insert on public.warehouse_temporary_sales_adjustments to authenticated;

drop policy if exists warehouse_temporary_sales_adjustments_authenticated_select
  on public.warehouse_temporary_sales_adjustments;

create policy warehouse_temporary_sales_adjustments_authenticated_select
on public.warehouse_temporary_sales_adjustments
for select to authenticated
using (true);

drop policy if exists warehouse_temporary_sales_adjustments_authenticated_insert
  on public.warehouse_temporary_sales_adjustments;

create policy warehouse_temporary_sales_adjustments_authenticated_insert
on public.warehouse_temporary_sales_adjustments
for insert to authenticated
with check (true);
