-- Temporary Sales Area items and auditable warehouse movements.
-- Run this script in Supabase before using the Temporary Sales actions.

create table if not exists public.warehouse_temporary_sales_items (
  id bigint generated by default as identity primary key,
  source_warehouse_storage_id bigint references public.warehouse_storage(id) on delete set null,
  source_pl_packing_item_id bigint references public.pl_packing_items(id) on delete set null,
  sku_id text,
  item_name text not null,
  size text,
  group_code text,
  area_type text not null default 'SALES',
  source_location_label text,
  qty_in_area numeric not null default 0 check (qty_in_area >= 0),
  status text not null default 'WAITING',
  entered_at timestamptz not null default now(),
  due_at timestamptz not null default (now() + interval '7 days'),
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint warehouse_temporary_sales_items_status_check
    check (status in ('WAITING', 'IN_TEMPORARY_AREA', 'NOT_REQUIRED', 'RETURNED', 'COMPLETED')),
  constraint warehouse_temporary_sales_items_area_type_check
    check (area_type in ('SALES', 'RETUR_KEEPING'))
);

create table if not exists public.warehouse_storage_movements (
  id bigint generated by default as identity primary key,
  -- Keep the historical source row id even after the warehouse row is consumed.
  warehouse_storage_id bigint,
  temporary_sales_item_id bigint references public.warehouse_temporary_sales_items(id) on delete set null,
  movement_type text not null,
  qty numeric not null check (qty > 0),
  from_location_label text,
  to_location_label text,
  item_name text,
  size text,
  sku_id text,
  created_by text,
  created_at timestamptz not null default now(),
  constraint warehouse_storage_movements_type_check
    check (movement_type in ('STORE_QUEUE', 'MOVE', 'TAKE_OUT', 'TEMPORARY_IN', 'TEMPORARY_RETURN'))
);

-- Physical count reconciliation for Temporary Sales Area discrepancies.
create table if not exists public.warehouse_temporary_sales_adjustments (
  id bigint generated by default as identity primary key,
  temporary_sales_item_id bigint not null references public.warehouse_temporary_sales_items(id) on delete cascade,
  system_qty numeric not null check (system_qty >= 0),
  actual_qty numeric not null check (actual_qty >= 0),
  variance_qty numeric not null,
  reason text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists warehouse_temporary_sales_adjustments_item_idx
  on public.warehouse_temporary_sales_adjustments (temporary_sales_item_id, created_at desc);

create index if not exists warehouse_temporary_sales_items_status_idx
  on public.warehouse_temporary_sales_items (status, due_at desc);

create index if not exists warehouse_temporary_sales_items_source_idx
  on public.warehouse_temporary_sales_items (source_warehouse_storage_id);

create index if not exists warehouse_storage_movements_created_at_idx
  on public.warehouse_storage_movements (created_at desc);

create index if not exists warehouse_storage_movements_temporary_item_idx
  on public.warehouse_storage_movements (temporary_sales_item_id, created_at desc);

-- Existing installations may still have the old FK. Movement history must remain
-- valid after a source warehouse_storage row is deleted.
alter table public.warehouse_storage_movements
  drop constraint if exists warehouse_storage_movements_warehouse_storage_id_fkey;

alter table public.warehouse_storage_movements
  drop constraint if exists warehouse_storage_movements_type_check;

alter table public.warehouse_storage_movements
  add constraint warehouse_storage_movements_type_check
  check (movement_type in ('STORE_QUEUE', 'MOVE', 'TAKE_OUT', 'TEMPORARY_IN', 'TEMPORARY_RETURN', 'TEMPORARY_ADJUSTMENT_IN', 'TEMPORARY_ADJUSTMENT_OUT'));

alter table public.warehouse_temporary_sales_items
  add column if not exists source_pl_packing_item_id bigint references public.pl_packing_items(id) on delete set null;

alter table public.warehouse_temporary_sales_items
  add column if not exists category_id bigint;

alter table public.warehouse_temporary_sales_items
  add column if not exists area_type text not null default 'SALES';

update public.warehouse_temporary_sales_items
set area_type = 'SALES'
where area_type is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.warehouse_temporary_sales_items'::regclass
      and conname = 'warehouse_temporary_sales_items_area_type_check'
  ) then
    alter table public.warehouse_temporary_sales_items
      add constraint warehouse_temporary_sales_items_area_type_check
      check (area_type in ('SALES', 'RETUR_KEEPING'));
  end if;
end $$;

create index if not exists warehouse_temporary_sales_items_area_type_idx
  on public.warehouse_temporary_sales_items (area_type, status, due_at desc);

create index if not exists warehouse_temporary_sales_items_category_idx
  on public.warehouse_temporary_sales_items (category_id);

alter table public.warehouse_temporary_sales_items enable row level security;
alter table public.warehouse_storage_movements enable row level security;
alter table public.warehouse_temporary_sales_adjustments enable row level security;

grant select, insert, update, delete on public.warehouse_temporary_sales_items to authenticated;
grant select, insert on public.warehouse_storage_movements to authenticated;
grant select, insert on public.warehouse_temporary_sales_adjustments to authenticated;

drop policy if exists warehouse_temporary_sales_items_authenticated_all
  on public.warehouse_temporary_sales_items;
create policy warehouse_temporary_sales_items_authenticated_all
on public.warehouse_temporary_sales_items
for all to authenticated
using (true)
with check (true);

drop policy if exists warehouse_storage_movements_authenticated_select_insert
  on public.warehouse_storage_movements;
create policy warehouse_storage_movements_authenticated_select_insert
on public.warehouse_storage_movements
for select to authenticated
using (true);

drop policy if exists warehouse_storage_movements_authenticated_insert
  on public.warehouse_storage_movements;
create policy warehouse_storage_movements_authenticated_insert
on public.warehouse_storage_movements
for insert to authenticated
with check (true);

drop policy if exists warehouse_temporary_sales_adjustments_authenticated_select_insert
  on public.warehouse_temporary_sales_adjustments;
create policy warehouse_temporary_sales_adjustments_authenticated_select_insert
on public.warehouse_temporary_sales_adjustments
for select to authenticated
using (true);

drop policy if exists warehouse_temporary_sales_adjustments_authenticated_insert
  on public.warehouse_temporary_sales_adjustments;
create policy warehouse_temporary_sales_adjustments_authenticated_insert
on public.warehouse_temporary_sales_adjustments
for insert to authenticated
with check (true);
